# Generated by Django 4.2.7 on 2026-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentvitals',
            name='activity_level',
        ),
        migrations.AddField(
            model_name='residentvitals',
            name='activity_status',
            field=models.CharField(choices=[('standing', 'Standing'), ('sitting', 'Sitting'), ('walking', 'Walking'), ('lying_down', 'Lying Down')], default='lying_down', max_length=20),
        ),
        migrations.AddField(
            model_name='residentvitals',
            name='in_bed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentvitals',
            name='in_room',
            field=models.BooleanField(default=True),
        ),
    ]
