# Generated by Django 4.2.7 on 2026-03-01 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_remove_residentvitals_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('caregiver_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notes', to='analytics.resident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
