# Generated by Django 4.2.7 on 2026-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alertnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='alert_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
