# Generated by Django 4.2.7 on 2026-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_resident_alert_dismissed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentvitals',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
